import * as THREE from 'three';

export const SKINS = [
    {
        id: 'classic',
        name: 'Klasik Neon',
        icon: '🟢',
        reqScore: 0,
        desc: 'Varsayılan yüksek enerjili cyan yılan',
        headColor: 0x00ffcc,
        bodyColor: 0x0099ff,
        emissiveIntensity: 0.5,
        roughness: 0.2,
        metalness: 0.5,
        transparent: false,
        opacity: 1.0,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'bubble',
        name: 'Köpük',
        icon: '🫧',
        reqScore: 50,
        desc: 'Saydam su baloncuklarından oluşan parlak köpük',
        headColor: 0x7dd3fc,
        bodyColor: 0x38bdf8,
        emissiveIntensity: 0.3,
        roughness: 0.1,
        metalness: 0.1,
        transparent: true,
        opacity: 0.65,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'bubblegum',
        name: 'Bubble Gum',
        icon: '🍬',
        reqScore: 120,
        desc: 'Tatlı pembe ve mor şeker gradyanı',
        headColor: 0xf472b6,
        bodyColor: 0xc084fc,
        emissiveIntensity: 0.4,
        roughness: 0.3,
        metalness: 0.2,
        transparent: false,
        opacity: 1.0,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'medieval',
        name: 'Şövalye Zırhı',
        icon: '🛡️',
        reqScore: 250,
        desc: 'Ortaçağ dövme çelik ve altın kaplama zırh',
        headColor: 0x64748b,
        bodyColor: 0x334155,
        emissiveIntensity: 0.2,
        roughness: 0.3,
        metalness: 0.95,
        transparent: false,
        opacity: 1.0,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'cyberpunk',
        name: 'Cyberpunk',
        icon: '⚡',
        reqScore: 400,
        desc: 'Neon yeşil ve magenta matrix veri akışı',
        headColor: 0x39ff14,
        bodyColor: 0xff007f,
        emissiveIntensity: 0.8,
        roughness: 0.1,
        metalness: 0.6,
        transparent: false,
        opacity: 1.0,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'fire',
        name: 'Ateşli Magma',
        icon: '🔥',
        reqScore: 600,
        desc: 'Kordan akkor lav ve volkanik kor parçaları',
        headColor: 0xff3300,
        bodyColor: 0xff8800,
        emissiveIntensity: 0.9,
        roughness: 0.4,
        metalness: 0.3,
        transparent: false,
        opacity: 1.0,
        hasHorns: true,
        hasCrown: false
    },
    {
        id: 'ghost',
        name: 'Ruhani Hayalet',
        icon: '👻',
        reqScore: 850,
        desc: 'Gece karanlığında süzülen yarı saydam hayalet',
        headColor: 0xa7f3d0,
        bodyColor: 0x6ee7b7,
        emissiveIntensity: 0.7,
        roughness: 0.1,
        metalness: 0.1,
        transparent: true,
        opacity: 0.45,
        hasHorns: false,
        hasCrown: false
    },
    {
        id: 'dragon',
        name: 'Antik Ejderha',
        icon: '🐉',
        reqScore: 1100,
        desc: 'Sert ejderha pulları ve korkusuz ejder boynuzları',
        headColor: 0x059669,
        bodyColor: 0xd97706,
        emissiveIntensity: 0.5,
        roughness: 0.3,
        metalness: 0.7,
        transparent: false,
        opacity: 1.0,
        hasHorns: true,
        hasCrown: false
    },
    {
        id: 'gold',
        name: 'Altın Kraliyet',
        icon: '🏆',
        reqScore: 1500,
        desc: '24 Ayar saf safir ve altın kraliyet görünüşü',
        headColor: 0xfcb316,
        bodyColor: 0xf59e0b,
        emissiveIntensity: 0.7,
        roughness: 0.25,
        metalness: 0.98,
        transparent: false,
        opacity: 1.0,
        hasHorns: false,
        hasCrown: true
    },
    {
        id: 'diamond',
        name: 'Kristal Elmas',
        icon: '💎',
        reqScore: 2000,
        desc: 'Işığı kıran kusursuz prizmatik elmas kaplama',
        headColor: 0xe0f2fe,
        bodyColor: 0xbae6fd,
        emissiveIntensity: 0.85,
        roughness: 0.05,
        metalness: 0.9,
        transparent: true,
        opacity: 0.85,
        hasHorns: true,
        hasCrown: true
    }
];

export function getSkinById(skinId) {
    return SKINS.find(s => s.id === skinId) || SKINS[0];
}
